JSWebPlay/Controllers/GameController.cs
using System.Web.Mvc;
using JSWebPlay.Services.Implementations;
using JSWebPlay.Services.Interfaces;

namespace JSWebPlay.Controllers
{
    public class GameController : Controller
    {
        private IGameService _gameService;

        public GameController() {
            _gameService = new GameService();
        }

        //
        // GET: /Game/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Jeopardy() {
            return View();
        }

        public ActionResult Maze() {
            return View();
        }

        //Ajax
        public ActionResult GetJeopardyBoard() {
            object gdata = _gameService.GetBoardData();
            
            JsonResult result = new JsonResult();
            result.Data = gdata;
            return result;
        }
    }
}

JSWebPlay/Controllers/GraphController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JSWebPlay.Controllers
{
    public class GraphController : Controller
    {
        //
        // GET: /Graph/

        public ActionResult Graph2d()
        {
            return View();
        }

    }
}

JSWebPlay/Controllers/HomeController.cs
using System.Web.Mvc;

namespace JSWebPlay.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Fib() {
            return View();
        }

        public ActionResult Factorial() {
            return View();
        }
        public ActionResult CssTests() {
            return View();
        }
    }
}

JSWebPlay/Controllers/OrgController.cs
using System.Web.Mvc;
using OrgServices.Repositories.Implementations;
using OrgServices.Repositories.Interfaces;
using OrgServices.Services.Implementations;
using OrgServices.Services.Interfaces;

namespace JSWebPlay.Controllers {
    public class OrgController : Controller {

        private const string XmlFile = @"C:\Source\Javascript\Html5Explorations\JSWebPlay\Content\Data\EmpInfo-03.xml";

        public ActionResult Index() {
            return View();
        }

        public ActionResult Scale() {
            return View();
        }

        public ActionResult ViewOrg() {
            return View();
        }

        public ActionResult LoadOrgData() {
            IEmployeeRepository employeeRepository = new XmlEmployeeRepository(XmlFile);
            IOrgService orgService = new OrgService(employeeRepository);

            var employeeList = orgService.GetEmployeeList();
            JsonResult result = new JsonResult();
            var data = employeeList;
            result.Data = data;
            return result;
        }
    }
}

JSWebPlay/Controllers/SketchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JSWebPlay.Controllers
{
    public class SketchController : Controller
    {
        public ActionResult Spirograph() {
            return View();
        }

    }
}

JSWebPlay/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Games</h2>

<ul>
    <li>@Html.ActionLink("Jeopardy - Klein 75", "Jeopardy")</li>
</ul>

JSWebPlay/Views/Game/Jeopardy.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>Klein Jeopardy 75</title>
    <link href="@Url.Content("~/Content/Games/Jeopardy.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Games/GameData.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Games/Jeopardy.js")" type="text/javascript"></script>
</head>
<body>
    <header>
        <img id="headshot1" class="headshot" src="@Url.Content("~/Content/Images/rpk-headshot-3.png")" alt="RPK"/>
        <section id="headers">
            <h1>
                Klein Jeopardy 75</h1>
        </section>
        <img id="headshot2" class="headshot" src="@Url.Content("~/Content/Images/rpk-headshot-3.png")" alt="RPK"/>
        <div class="clear">
        </div>
    </header>
    <section id="boardSection">
        <audio id="barbara01" src="@Url.Content("~/Content/Audio/barbara-01.mp3")"></audio>
        <audio id="idiot01" src="@Url.Content("~/Content/Audio/idiot.mp3")"></audio>
        <audio id="lostkeys" src="@Url.Content("~/Content/Audio/lostkeys.mp3")" ></audio>
        <div id="revealedQuestion">
            <div id="questionText">
                The question is...
            </div>
            <div id="revealedButtons">
                <input id="CtlRevealAnswerBtn" type="button" value="And the answer is..." />
            </div>
        </div>
        <div id="revealedAnswer">
            <div id="answerText">
                The answer is...
            </div>
            <div id="revealedAnswerButtons">
                <input id="CtlRevealedAnswerCloseBtn" type="button" value="OK" />
            </div>
        </div>
        <div id="bigRichard">
            <img id="bigRichardImg" src="@Url.Content("~/Content/Images/dicky face.png")" alt="RPK"/>
        </div>
        <table id="cardTable">
            <thead id="categoryHeader">
            </thead>
            <tbody>
            </tbody>
        </table>
    </section>
    <section id="controlBarSection">
        <input type="button" id="CBtnStartGameBtn" class="controlButton" value="Start" />
        <input type="button" id="CBtnWrong" class="controlButton" value="Wrong" />
        <input type="button" id="CBtnBarbara" class="controlButton" value="Barbara!" />
    </section>
</body>
</html>

JSWebPlay/Views/Game/Maze.cshtml
@model object
@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/Games/Maze.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/Games/Maze.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/Stack.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/MazeGame.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/Point.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/Door.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/Wall.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/Cell.js")" type="text/javascript"></script>
<div id="board">
    <section id="inputPanel">
        <label>
            Size:</label><input id="ctlSize" name="ctlSize" type="number" value="40" min="2" max="90" />
        <input type="button" id="CtlDrawMaze" value="Draw Maze" />
        <input type="button" id="CtlSolveMaze" value="Solve" />
        <input type="button" id="CtlErasePath" value="Erase" />
    </section>
    <canvas id="maze">
    </canvas>
</div>

JSWebPlay/Views/Graph/Graph2d.cshtml
@{
    ViewBag.Title = "Graph2d";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/Graph/Graph2d.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Shared/Matrix.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Home/CalcLib.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Graph/GraphModule.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Graph/Plotter.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Graph/MovieMaker.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Graph/Graph2d.js")" type="text/javascript"></script>
<section id="inputSection">
    <div id="d2Inputs" class="d2Control">
        <div class="eqDiv">
            <div class="equationsFAndG">
                <div class="equationF">
                    <label class="dependentVariable">
                        f(x)=</label><input id="eq1" type="text" class="eqInput" />
                </div>
                <div id="equationG">
                    <label class="dependentVariable">
                        g(x)=</label><input id="eq2" type="text" class="eqInput" />
                </div>
            </div>
            <div class="controlButtons">
                <input type="button" id="plotButton" value="Plot" />
                <input type="button" id="switchTo3dBtn" value="Switch to 3D" />
            </div>
        </div>
    </div>
    <div id="d3Inputs" class="d3Control">
        <div class="eqDiv">
            <div class="equationsFAndG">
                <div class="equationF">
                    <label class="dependentVariable">
                        f(x,y)=</label><input id="eq1_3d" type="text" class="eqInput" />
                </div>
                <div id="equationG">
                    <label class="dependentVariable">
                        g(x,y)=</label><input id="eq2_3d" type="text" class="eqInput" />
                </div>
            </div>
            <div class="controlButtons">
                <input type="button" id="plot3dButton" value="Plot" />
                <input type="button" id="switchTo2dBtn" value="Switch to 2D" />
            </div>
        </div>
    </div>
</section>
<section id="plotSection">
</section>
<section id="controlsSection">
    <div id="domainControl" class="domainRangeControl d2Control">
        <label>
            X:</label>
        <span class="value" id="lblXMin">0</span>
        <label>
            to
        </label>
        <span id="lblXMax" class="value">0</span>
        <div id="domainSlider" class="domainRangeSlider">
        </div>
        <div>
            <input type="checkbox" id="xPositiveOnly" />Positive Only</div>
    </div>
    <div id="rangeControl" class="domainRangeControl d2Control">
        <label>
            Y:</label>
        <span class="value" id="lblYMin">0</span>
        <label>
            to
        </label>
        <span id="lblYMax" class="value">0</span>
        <div id="rangeSlider" class="domainRangeSlider">
        </div>
    </div>
    <div id="numPointsDiv">
        <label>
            N:</label>
        <input type="number" id="numPoints" title="For 2D graphs, the number of points to plot.  For 3D graphs, the two-dimensional grid size over which Z is computed." />
    </div>
    <div id="rotationAngles" class="d3Control">
        <div class="rotationAngleDiv">
            <label>
                X:</label>
            <input id="xAngleRotation" class="rotationAngleInput" type="number" />
        </div>
        <div class="rotationAngleDiv">
            <label>
                Y:</label>
            <input id="yAngleRotation" class="rotationAngleInput" type="number" />
        </div>
        <div class="rotationAngleDiv">
            <label>
                Z:</label>
            <input id="zAngleRotation" class="rotationAngleInput" type="number" />
        </div>
        <div id="animationFieldsDiv">
            <fieldset id="animationFields">
                <legend>Animation</legend>
                <div id="animationButtons">
                    <input type="button" id="animateXBtn" value="X" />
                    <input type="button" id="animateYBtn" value="Y" />
                    <input type="button" id="animateZBtn" value="Z" />
                </div>
                <input type="button" id="stopAnimationBtn" value="Stop Animation" />
            </fieldset>
        </div>
    </div>
    <div id="imageControlDiv">
        <input type="button" id="captureImageButton" value="Capture Image" />
        <input type="button" id="pushFrameButton" value="Push Frame" />
        <input type="button" id="popFrameButton" value="Pop Frame" />
        <input type="button" id="playMovieButton" value="Play Movie" />
        <input type="button" id="clearMovieButton" value="Clear Movie" />
        <table id="colorGradientTable" class="d3Control">
            <thead>
                <tr>
                    <td>
                    </td>
                    <td>
                        R
                    </td>
                    <td>
                        G
                    </td>
                    <td>
                        B
                    </td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        Start:
                    </td>
                    <td>
                        <input type="number" id="redStart" value="0" />
                    </td>
                    <td>
                        <input type="number" id="greenStart" value="0" />
                    </td>
                    <td>
                        <input type="number" id="blueStart" value="0" />
                    </td>
                </tr>
                <tr>
                    <td>
                        End:
                    </td>
                    <td>
                        <input type="number" id="redEnd" value="0" />
                    </td>
                    <td>
                        <input type="number" id="greenEnd" value="0" />
                    </td>
                    <td>
                        <input type="number" id="blueEnd" value="0" />
                    </td>
                </tr>
            </tbody>
        </table>
        <div id="imageControlNumbers">
            <label for="frameRate">
                Rate:</label>
            <input type="number" id="frameRate" value="25" />
            <label for="animationFrameCount">
                An.Frames:</label>
            <input type="number" id="animationFrameCount" value="150" />
            <label for="frameCount">
                Frames:</label><span id="frameCount">0</span>
        </div>
    </div>
</section>
<section id="statusBarSection">
    <div id="statusBarMsgDiv">
        <span id="statusBarMsg">Plot messages...</span>
    </div>
</section>
<section id="imageCaptureSection">
    <div id="imageDiv">
    </div>
    <input type="button" id="imageCloseBtn" value="Close" />
</section>

JSWebPlay/Views/Home/CssTests.cshtml
@{
    ViewBag.Title = "CssTests";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Css Tests</h2>

<div style="border: solid 1px black">
    Outer text in div
    <div style="border: solid 1px yellow">
        Inner text
    </div>
</div>

JSWebPlay/Views/Home/Factorial.cshtml
@{
    ViewBag.Title = "Factorial";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Factorial</h2>
<script src="@Url.Content("~/Scripts/Home/Factorial.js")" type="text/javascript"></script>
@Html.Partial("_NumberForm");

JSWebPlay/Views/Home/Fib.cshtml
@{
    ViewBag.Title = "Fib";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Fib</h2>
<script src="@Url.Content("~/Scripts/Home/Fib.js")" type="text/javascript"></script>
@Html.Partial("_NumberForm");

JSWebPlay/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="intro">
Various explorations into HTML 5 and JavaScript.  Maze, Org Chart, and Spirograph show off some
of the new HTML 5 Canvas support.  Fibonacci and Factorial demonstrate memoization using javascript
closures.
</section>

JSWebPlay/Views/Home/_NumberForm.cshtml
<script src="@Url.Content("~/Scripts/Home/CalcLib.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Home/NumberForm.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Content/Home/NumberForm.css")" rel="stylesheet" type="text/css" />

<label>Number: </label><input type="text" name="CtlInputNumber" id="CtlInputNumber" size="20" />
<input type="button" id="CtlCalcBtn" value="Calc" />
<input type="button" id="CtlClearText" value="Clear"/>
<div class="clear" />

&nbsp;
<label>Result:</label>
<div id="CtlResult"></div>
<div class="clear" />

<div>
    <textarea id="CtlText" cols="80" rows="15"></textarea>
</div>

JSWebPlay/Views/Org/Index.cshtml
@model object

@{
    ViewBag.Title = "Organization";
}

JSWebPlay/Views/Org/Scale.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="@Url.Content("~/Content/Org/Org.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/Org/Org.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Org/Scale.js")" type="text/javascript"></script>

<h2>Scale Text</h2>
<canvas>
</canvas>

JSWebPlay/Views/Org/ViewOrg.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="@Url.Content("~/Content/Org/Org.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/Org/Org.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Org/OrgUtils.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Org/ViewOrg.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Games/Point.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Org/OrgDataParser.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Org/OrgCharter.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Org/BoundingRect.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Org/EmpDetailer.js")" type="text/javascript"></script>

<canvas>
</canvas>
<div id="empDetail">
    <h1><span id="infoDataName"></span></h1>
    <div id="empInfo">
        <div class="infoLine">
            <label>Title:</label>
            <span id="infoDataTitle" class="infoData"></span>
        </div>
        <div class="infoLine">
            <label>Office:</label>
            <span id="infoDataOffice" class="infoData"></span>
        </div>
        <div class="infoLine">
            <label>Supervisor:</label>
            <span id="infoDataSupervisor" class="infoData"></span>
        </div>
    </div>
    <hr/>
    <section id="empReports">
        <div id="directReports">
            <h1>Direct Reports</h1>
            <ul id="directReportsList">
            </ul>
        </div>
        <div id="inDirectReports">
            <h1>Indirect Reports</h1>
            <ul id="inDirectReportsList">
            </ul>
        </div>
    </section>
    <input type="button" id="closeEmpDetailBtn" value="Close"></input>
</div>

JSWebPlay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/Shared/site.js")" type="text/javascript"></script>
</head>
<body>
    <ul id="mainMenu">
@*
        <li><a href="#">Computation</a>
            <ul>
                <li>@Html.ActionLink("Fib", "Fib", "Home")</li>
                <li>@Html.ActionLink("Factorial", "Factorial", "Home")</li>
            </ul>
        </li>
*@
        <li><a href="#">Games</a>
            <ul>
                <li>@Html.ActionLink("Jeopardy", "Jeopardy", "Game")</li>
                <li>@Html.ActionLink("Maze", "Maze", "Game")</li>
            </ul>
        </li>
        <li>@Html.ActionLink("Org Chart", "ViewOrg", "Org")</li>
        <li>@Html.ActionLink("Spirographs", "Spirograph", "Sketch")</li>
        <li>@Html.ActionLink("Graphics", "Graph2d", "Graph")
        </li>
    </ul>
    <div class="clear"></div>
    @RenderBody()
</body>
</html>

JSWebPlay/Views/Sketch/Spirograph.cshtml
@{
    ViewBag.Title = "Spirograph";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="@Url.Content("~/Content/Sketch/Spirograph.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/Sketch/SketchDraw.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Sketch/Spirograph.js")" type="text/javascript"></script>

<section id="controlPanel">
    <section id="valueInputs">
        <div class="row">
            <label>
                Count:</label>
            <input type="number" id="ctlCount" min="1" max="100" value="100" />
        </div>
        <div class="row">
            <label>
                Size:</label>
            <input type="number" id="ctlSize" min="1" max="500" value="340" />
        </div>
    </section>

    <section id="shapeSelection">
        <input type="radio" id="ctlTriangle" name="shapeChoice" value="Triangle" />
        <label for="CtlTriangle">Triangle</label>
        <input type="radio" id="ctlSquare" name="shapeChoice" value="Square" />
        <label for="CtlSquare">Square</label>
        <input type="radio" id="ctlOval" name="shapeChoice" value="Oval" checked="checked" />
        <label for="CtlOval">Oval</label>
        <div class="clear"></div>
    </section>

    <input type="button" id="CtlDraw" value="Draw" />

</section>
<canvas>
</canvas>